export const initialPolls = [
  {
    id: 1,
    title: "ABC Ltd — CoC Vote",
    type: "Insolvency",
    status: "DRAFT",
    startTime: "2025-09-12T10:00:00",
    endTime: "2025-09-12T18:00:00",
    questions: [],
    settings: { allowSkip: false, weightedVotes: true },
    voters: [],
  },
  {
    id: 2,
    title: "Q3 Shareholder Vote",
    type: "Shareholder",
    status: "OPEN",
    startTime: "2025-09-15T09:00:00",
    endTime: "2025-09-15T17:00:00",
    originalEndTime: "2025-09-15T17:00:00",
    questions: [
      {
        id: 1,
        text: "Approve the Q3 financial report.",
        attachment: null,
        options: ["Approve", "Reject", "Abstain"],
        enabledOptions: ["Approve", "Reject", "Abstain"],
      },
      {
        id: 2,
        text: "Elect new board member: Ms. Priya Sharma.",
        attachment: null,
        options: ["Approve", "Reject", "Abstain"],
        enabledOptions: ["Approve", "Reject", "Abstain"],
      },
    ],
    settings: { allowSkip: true, weightedVotes: true },
    voters: [
      {
        id: 1,
        email: "a.kulkarni@example.com",
        name: "Asha Kulkarni",
        weight: 1.0,
        hasVoted: true,
      },
      {
        id: 2,
        email: "r.patil@example.com",
        name: "Ravi Patil",
        weight: 2.5,
        hasVoted: true,
      },
      {
        id: 3,
        email: "s.mehta@example.com",
        name: "Suresh Mehta",
        weight: 1.75,
        hasVoted: false,
      },
      {
        id: 4,
        email: "p.gupta@example.com",
        name: "Priya Gupta",
        weight: 1.0,
        hasVoted: true,
      },
      {
        id: 5,
        email: "v.singh@example.com",
        name: "Vikram Singh",
        weight: 3.0,
        hasVoted: false,
      },
    ],
    votes: [
      { voterId: 1, questionId: 1, option: "Approve" },
      { voterId: 1, questionId: 2, option: "Approve" },
      { voterId: 2, questionId: 1, option: "Reject" },
      { voterId: 2, questionId: 2, option: "Abstain" },
      { voterId: 4, questionId: 1, option: "Approve" },
    ],
  },
  // ... other polls
];
